services:
  - type: web
    name: task-manager-api
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://task-manager-api.onrender.com
    healthCheckPath: /api/auth/me
    autoDeploy: true
