services:
  - type: web
    name: task-manager-api
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "https://task-manager-rho-virid.vercel.app"
    healthCheckPath: /health
    autoDeploy: true

  - type: web
    name: task-manager-frontend
    env: static
    plan: free
    buildCommand: echo "Frontend files ready"
    startCommand: echo "Static site deployed"
    staticPublishPath: ./frontend
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
